
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    kubernetes.io/metadata.name: demo
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/display-name: "Demo"
    openshift.io/requester: admin
