apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-downloader
  namespace: model-downloads
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-downloader
  namespace: model-downloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: model-downloader
subjects:
  - kind: ServiceAccount
    name: model-downloader
    namespace: model-downloads
