apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-downloader
  namespace: model-downloads
  labels:
    app.kubernetes.io/name: model-downloader
    app.kubernetes.io/part-of: rhoai-demos
  annotations:
    argocd.argoproj.io/sync-wave: "0"