{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-storage
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
{{- if .Values.postgresql.storage.storageClassName }}
  storageClassName: {{ .Values.postgresql.storage.storageClassName }}
{{- end }}
{{- end }}
