{{- if .Values.searxng.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: searxng-service
  namespace: {{ .Values.namespace }}
  labels:
    app: searxng
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.searxng.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: searxng
{{- end }}
