apiVersion: v1
kind: ServiceAccount
metadata:
  name: surfsense
  namespace: {{ .Values.namespace }}
  labels:
    app: surfsense
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.surfsense: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"surfsense"}}'
    argocd.argoproj.io/sync-wave: "1"
