apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-vl-8b-model-storage
  namespace: model-downloads
  labels:
    app.kubernetes.io/name: qwen3-vl-8b
    app.kubernetes.io/part-of: rhoai-demos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
