apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: surfsense
  namespace: demo-apps
  labels:
    app: surfsense
spec:
  to:
    kind: Service
    name: surfsense-oauth-proxy
  port:
    targetPort: oauth-proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
