apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-dependencies
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: rhoai-dependencies
    app.kubernetes.io/part-of: rhoai-platform
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-app-demos
    targetRevision: main
    path: platform/rhoai-operator/dependencies
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
