apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: rhoai-operator
    app.kubernetes.io/part-of: rhoai-demos
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-app-demos.git
    targetRevision: main
    path: platform/rhoai-operator
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: datasciencecluster.opendatahub.io
      kind: DataScienceCluster
      jsonPointers:
        - /spec/components/*/devFlags
