apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-machineset-aws-g6
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: gpu-machineset-aws
    app.kubernetes.io/part-of: rhoai-demos
    app.kubernetes.io/component: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ai-americas/rhoai-app-demos.git
    targetRevision: main
    path: infra/gpu-machineset/aws/overlays/g6-2xlarge
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-machine-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
