apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anythingllm
  namespace: anythingllm
  labels:
    app: anythingllm
spec:
  to:
    kind: Service
    name: anythingllm
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
